import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { barlow, barlowCondensed, bellefair } from "./fonts/fonts";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: [
		{
			url: "/favicon.ico",
			sizes: "32x32",
			type: "image/x-icon",
		},
	],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${bellefair.variable} ${barlow.variable} ${barlowCondensed.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
